---
- name: Install packages on VM
  hosts: myvms
  become: yes
  tasks:
    - name: Install Git
      ansible.builtin.package:
        name: git
        state: present

    - name: Install Apache2
      ansible.builtin.package:
        name: apache2
        state: present

    - name: Install net-tools
      ansible.builtin.package:
        name: net-tools
        state: present
