---
- name: Setup and configure VM
  hosts: myvms
  become: yes
  vars:
    web_content: |
      <html>
        <head><title>Welcome to My Engaging Site!</title></head>
        <body>
          <h1>Welcome to My Engaging Website</h1>
          <p>This site is brought to you by Ansible automation!</p>
        </body>
      </html>
  tasks:
    - name: Install Git, Apache2, and net-tools
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - apache2
        - net-tools

    - name: Create an engaging index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: "{{ web_content }}"

    - name: Ensure Apache is running
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

